# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.3.4

executors:
  ios:
    macos:
      xcode: 14.2.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    environment:
      FL_OUTPUT_DIR: output
      LANG: en_US.UTF-8

jobs:
  unit_test:
    executor: ios
    steps:
      - macos/preboot-simulator:
          version: "16.0"
          platform: "iOS"
          device: "iPhone 14"
      - run_lane:
          lane: unit_test
      # - store_artifacts:
      #     path: output
      - store_test_results:
          path: output/scan

commands:
  run_lane:
    description: "Run specifc lane using Fastlane"
    parameters:
      lane:
        type: string
    steps:
      - checkout
      - run:
          name: "Run lane in Fastlane"
          command: bundle exec fastlane ${{parameters.lane}}

workflows:
  run_unit_tests:
    jobs:
      - unit_test
      # - adhoc:
      #     filters:
      #       branches:
      #         only: development
      #     requires:
      #       - build-and-test
