# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.3.4

executors:
  ios:
    macos:
      xcode: 14.2.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    environment:
      FL_OUTPUT_DIR: output
      LANG: en_US.UTF-8

jobs:
  unit_test:
    executor: ios
    environment:
      IOS_DEVICE: iPhone 14
      IOS_VERSION: 16.2
    steps:
      - run:
          name: "Ruby version"
          command: ruby -v
      # - run:
      #     name: Pre-boot iOS Simulator
      #     command: |
      #       UDID=$(xcrun xctrace list devices 2>&1 | grep "$IOS_DEVICE Simulator ($IOS_VERSION) (" | awk -F'[()]' '{print $4}')
      #       xcrun simctl boot "$UDID"
      # - run_lane:
      #     lane: unit_test
      # # - store_artifacts:
      # #     path: output
      # - store_test_results:
      #     path: output/scan

commands:
  run_lane:
    description: "Run specifc lane using Fastlane"
    parameters:
      lane:
        type: string
    steps:
      - checkout
      - macos/switch-ruby:
          version: 2.7.2
      - run:
          name: Install gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: "Run lane in Fastlane"
          command: bundle exec fastlane << parameters.lane >>

workflows:
  run_unit_tests:
    jobs:
      - unit_test
      # - adhoc:
      #     filters:
      #       branches:
      #         only: development
      #     requires:
      #       - build-and-test
