fastlane_require 'dotenv'

default_platform(:ios)

before_all do
    Dotenv.load('.env.secret')
end

lane :produce_app do 
    create_app_online
end

platform :ios do
    before_all do
        Dotenv.load('.env.ios')
    end

    desc "Sync and sign certificates"
    lane :load_codesign do
        sync_code_signing
    end

    desc "Build and sign the app"
    lane :build do
        load_codesign

        build_ios_app
    end

    desc "Build and upload the app to TestFlight"
    lane :upload_for_testing do
        build

        upload_to_testflight
    end
end